controllers/AccountController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Account;
use app\models\AccountSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\AccessRule;
use yii\filters\AccessControl;

/**
 * AccountController implements the CRUD actions for Account model.
 */
class AccountController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                'access' => [
                   'class' => AccessControl::className(),
                   // We will override the default rule config with the new AccessRule class
                   'ruleConfig' => [
                       'class' => AccessRule::className(),
                   ],
                   'only' => ['index','create', 'update', 'delete'],
                   'rules' => [
                       [
                           'actions' => ['index','create', 'update', 'delete'],
                           'allow' => true,
                           // Allow admins to crud
                           'roles' => [
                               User::ROLE_ADMIN
                           ],
                       ],
                   ],
                ], 
            ]
        );
    }

    /**
     * Lists all Account models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new AccountSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        $dataProvider->pagination->pageSize=5;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Account model.
     * @param int $account_id Account ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($account_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($account_id),
        ]);
    }

    /**
     * Creates a new Account model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Account();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->role   = 'author';
                $model->status = 10;

                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Akun baru berhasil ditambahkan.');
                    return $this->redirect(['index']);
                }
                //return $this->redirect(['view', 'account_id' => $model->account_id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Account model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $account_id Account ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($account_id)
    {
        $model = $this->findModel($account_id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Akun '.$model->name.' berhasil diupdate');
            return $this->redirect(['index']);
            //return $this->redirect(['view', 'account_id' => $model->account_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Account model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $account_id Account ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($account_id)
    {   
        $model = $this->findModel($account_id);
        $this->findModel($account_id)->delete();

        Yii::$app->session->setFlash('success', 'Akun '.$model->name.' berhasil dihapus.');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Account model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $account_id Account ID
     * @return Account the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($account_id)
    {
        if (($model = Account::findOne(['account_id' => $account_id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\PostSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\AccessRule;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                'access' => [
                   'class' => AccessControl::className(),
                   // We will override the default rule config with the new AccessRule class
                   'ruleConfig' => [
                       'class' => AccessRule::className(),
                   ],
                   'only' => ['index','create', 'update', 'delete'],
                   'rules' => [
                       [
                           'actions' => ['index','create', 'update'],
                           'allow' => true,
                           // Allow admins & author to cru
                           'roles' => [
                               User::ROLE_ADMIN,
                               User::ROLE_AUTHOR,
                           ],
                       ],
                       [
                           'actions' => ['delete'],
                           'allow' => true,
                           // Allow admins to delete
                           'roles' => [
                               User::ROLE_ADMIN,
                           ],
                       ],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Post models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        $dataProvider->pagination->pageSize=10;

        $category = ArrayHelper::map(\app\models\Category::find()->where(['category_active' => '1'])->orderBy('category')->asArray()->all(), 'category_id', 'category');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'category'  => $category,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param int $idpost Idpost
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idpost)
    {
        return $this->render('view', [
            'model' => $this->findModel($idpost),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Post();
        $category = ArrayHelper::map(\app\models\Category::find()->where(['category_active' => '1'])->orderBy('category')->asArray()->all(), 'category_id', 'category');

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->account_id = \Yii::$app->user->identity->account_id;
                $model->date       = date('Y-m-d');
                
                $cover = UploadedFile::getInstance($model, 'cover');

                if($model->validate()){
                    if (!empty($cover)) {
                        $saveTo = 'uploads/post/'.$cover->baseName.'.'.$cover->extension;

                        $cover->saveAs($saveTo);
                        $model->cover = $cover->baseName.'.'. $cover->extension;
                        $model->save(FALSE);
                    }
                }

                $model->save();
                Yii::$app->session->setFlash('success', 'Post baru berhasil ditambahkan.');
                return $this->redirect(['index']);

            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'category' => $category
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $idpost Idpost
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idpost)
    {
        $model = $this->findModel($idpost);
        $category = ArrayHelper::map(\app\models\Category::find()->where(['category_active' => '1'])->orderBy('category')->asArray()->all(), 'category_id', 'category');

        if ($this->request->isPost && $model->load($this->request->post())) {

            $cover = UploadedFile::getInstance($model, 'cover');

            if($model->validate()){
                if (!empty($cover)) {
                    $saveTo = 'uploads/post/'.$cover->baseName.'.'.$cover->extension;

                    $cover->saveAs($saveTo);
                    $model->cover = $cover->baseName.'.'. $cover->extension;
                    $model->save(FALSE);
                }
            }

            $model->save();
            Yii::$app->session->setFlash('success', 'Post '.$model->title.' berhasil diupdate.');
            return $this->redirect(['index']);
            //return $this->redirect(['view', 'idpost' => $model->idpost]);
            
        }

        return $this->render('update', [
            'model' => $model,
            'category' => $category,
        ]);
    }

    public function actionVerification($idpost)
    {
        $model = $this->findModel($idpost);

        $model->verification_status = Post::STATUS_VERIFICATION;
        $model->verification_date   = date('Y-m-d H:i:s');
        $model->save();
        Yii::$app->session->setFlash('success', 'Post '.$model->title.' berhasil diverifikasi.');
        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $idpost Idpost
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idpost)
    {   
        $model = $this->findModel($idpost);
        $this->findModel($idpost)->delete();

        Yii::$app->session->setFlash('success', 'Post '.$model->title.' berhasil dihapus');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $idpost Idpost
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idpost)
    {
        if (($model = Post::findOne(['idpost' => $idpost])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */

// use yii\helpers\Html;
// use yii\bootstrap4\Breadcrumbs;

// $bundle = yiister\gentelella\assets\Asset::register($this);

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);

?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="<?= Yii::$app->request->baseUrl; ?>/uploads/favicon.ico" type="image/x-icon" />
    <?php $this->head() ?>
</head>
<body class="nav-<?= !empty($_COOKIE['menuIsCollapsed']) && $_COOKIE['menuIsCollapsed'] == 'true' ? 'sm' : 'md' ?>" >
<?php $this->beginBody(); ?>
<div class="container body">

    <div class="main_container">

        <div class="col-md-3 left_col menu_fixed">
            <div class="left_col scroll-view">

                <div class="navbar nav_title" style="border: 0;">
                    <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Gentellela Alela!</span></a>
                </div>
                <div class="clearfix"></div>

                <!-- menu prile quick info -->
                <div class="profile">
                    <div class="profile_pic">
                        <img src="https://colorlib.com/polygon/gentelella/images/img.jpg" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2><?= Yii::$app->user->identity->name?></h2>
                    </div>
                </div>
                <!-- /menu prile quick info -->

                <br />

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <?php
                        if (isset(Yii::$app->user->identity->role) && Yii::$app->user->identity->role == 'admin') {
                            $menu = [
                                        ["label" => "Home", "url" => ["site/index"], "icon" => "home"],
                                        ["label" => "Akun", "url" => ["account/index"], "icon" => "fas fa-user"],
                                        ["label" => "Post", "url" => ["post/index"], "icon" => "fas fa-book"],
                                    ];
                        }
                        else if (isset(Yii::$app->user->identity->role) && Yii::$app->user->identity->role == 'author') {
                            $menu = [
                                        ["label" => "Home", "url" => ["site/index"], "icon" => "home"],
                                        ["label" => "Post", "url" => ["post/index"], "icon" => "fas fa-book"],
                                    ];
                        }
                    ?>
                    <div class="menu_section">
                        <h3>General</h3>
                        <?=
                        \yiister\gentelella\widgets\Menu::widget(
                            [
                                "items" => $menu,
                            ]
                        )
                        ?>
                    </div>

                </div>
                <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Settings">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Lock">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">

            <div class="nav_menu">
                <nav class="" role="navigation">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <img src="https://colorlib.com/polygon/gentelella/images/img.jpg" alt=""><?= Yii::$app->user->identity->name?>
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <!-- <li><a href="javascript:;">Profile</a>
                                </li> -->
                                <!-- <li>
                                    <a href="javascript:;">
                                        <span class="badge bg-red pull-right">50%</span>
                                        <span>Settings</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">Help</a>
                                </li> -->
                                <li>
                                    <?= Html::a(' Logout', ['site/logout'], ['data' => ['method' => 'post'], 'class' => 'fa fa-sign-out pull-right'])?>
                                    <!-- <a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a> -->
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>

        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <?php if (isset($this->params['h1'])): ?>
                <div class="page-title">
                    <div class="title_left">
                        <h1><?= $this->params['h1'] ?></h1>
                    </div>
                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="clearfix"></div>
            <?= 
               Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
               ]) 
            ?>
            <?= $content ?>
        </div>
        <!-- /page content -->
        <!-- footer content -->
        <footer>
            <div class="pull-right">
                Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com" rel="nofollow" target="_blank">Colorlib</a><br />
                Extension for Yii framework 2 by <a href="http://yiister.ru" rel="nofollow" target="_blank">Yiister</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>

</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
</div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/main_login.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */

// use yii\helpers\Html;
// use yii\bootstrap4\Breadcrumbs;

// $bundle = yiister\gentelella\assets\Asset::register($this);

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);

?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="<?= Yii::$app->request->baseUrl; ?>/uploads/favicon.ico" type="image/x-icon" />
    <?php $this->head() ?>
</head>
<body class="login" >
<?php $this->beginBody(); ?>
    <div class="container body">
        <div class="container">
            <div class="col-md-12">
                <?= $content ?>
            </div>
        </div>
    </div>

    <div id="custom_notifications" class="custom-notifications dsp_none">
        <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
        </ul>
        <div class="clearfix"></div>
        <div id="notif-group" class="tabbed_notifications"></div>
    </div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/main_old.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="<?= Yii::$app->request->baseUrl; ?>/uploads/favicon.ico" type="image/x-icon" />
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);

    if (isset(Yii::$app->user->identity->role) && Yii::$app->user->identity->role == 'admin') {
       $menu = [
            ['label' => 'Home', 'url' => ['/site/index']],
            
            ['label' => 'Account', 'url' => ['/account/index']],
            ['label' => 'Post', 'url' => ['/post/index']],
            
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ]; 
    }
    else if (isset(Yii::$app->user->identity->role) && Yii::$app->user->identity->role == 'author') {
        $menu = [
            ['label' => 'Home', 'url' => ['/site/index']],
            
            ['label' => 'Post', 'url' => ['/post/index']],
            
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ];
    } 
    else{
        $menu = [
            ['label' => 'Home', 'url' => ['/site/index']],
            
            // Yii::$app->user->isGuest ? (
            //     ['label' => 'Login', 'url' => ['/site/login']]
            // ) : (
            //     '<li>'
            //     . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
            //     . Html::submitButton(
            //         'Logout (' . Yii::$app->user->identity->username . ')',
            //         ['class' => 'btn btn-link logout']
            //     )
            //     . Html::endForm()
            //     . '</li>'
            // )
        ];
    }   

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => $menu,
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>